[project]
name = "packagetracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp==3.12.15",
    "python-dotenv==1.0.1",
    "semantic-kernel==1.35.2",
]
